base_images:
  ocp_4.20_base-rhel9:
    name: "4.20"
    namespace: ocp
    tag: base-rhel9
  ocp_builder_rhel-9-golang-1.24-openshift-4.20:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.24-openshift-4.20
build_root:
  from_repository: true
images:
- dockerfile_path: openshift/Dockerfile
  inputs:
    ocp_4.20_base-rhel9:
      as:
      - registry.ci.openshift.org/ocp/4.20:base-rhel9
    ocp_builder_rhel-9-golang-1.24-openshift-4.20:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.24-openshift-4.20
  to: openshift-ansible-operator-plugins
- dockerfile_path: openshift/ci/dockerfiles/ansible-e2e.Dockerfile
  from: openshift-ansible-operator-plugins
  to: ansible-operator-e2e
- dockerfile_path: openshift/Dockerfile.requirements
  inputs:
    ocp_4.20_base-rhel9:
      as:
      - registry.ci.openshift.org/ocp/4.20:base-rhel9
  to: build-requirements
- dockerfile_literal: |
    FROM build-requirements AS builder

    FROM src
    RUN rm openshift/requirements*.txt
    COPY --from=builder requirements*.txt openshift/
  from: src
  inputs:
    build-requirements:
      as:
      - build-requirements
  to: get-requirements
- dockerfile_path: openshift/release/ansible/Dockerfile.collections
  inputs:
    ocp_4.20_base-rhel9:
      as:
      - registry.ci.openshift.org/ocp/4.20:base-rhel9
  to: build-collections
- dockerfile_literal: |
    FROM build-collections AS builder

    FROM src
    RUN rm -r openshift/release/ansible/ansible_collections
    COPY --from=builder ansible_collections/ openshift/release/ansible/ansible_collections/
  from: src
  inputs:
    build-collections:
      as:
      - build-collections
  to: get-collections
promotion:
  to:
  - name: "4.20"
    namespace: ocp
releases:
  arm64-latest:
    candidate:
      architecture: arm64
      product: ocp
      stream: nightly
      version: "4.20"
  initial:
    integration:
      name: "4.20"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.20"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: |
    # Set $HOME for sufficient permission
    HOME=/tmp make test-unit
  container:
    from: src
- as: sanity
  commands: |
    # Set $HOME for golangci-lint cache
    HOME=/tmp make test-sanity
  container:
    from: src
- as: e2e-ansible
  steps:
    cluster_profile: gcp
    test:
    - as: test
      cli: latest
      commands: make -f openshift/Makefile test-e2e-ansible
      dependencies:
      - env: IMAGE_FORMAT
        name: ansible-operator-e2e
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: ipi-gcp
- as: verify-deps
  steps:
    env:
      CHECK_MOD_LIST: "false"
    test:
    - ref: go-verify-deps
- as: verify-requirements
  commands: |
    echo "Verify requirements: running git diff to detect changes..."
    git diff --exit-code
  container:
    from: get-requirements
  run_if_changed: ^(images/ansible-operator/Pipfile*|openshift/install-ansible.sh|openshift/requirements*.txt|openshift/Dockerfile.requirements)$
- as: verify-collections
  commands: |
    echo "Verify ansible-collections: running git diff to detect changes..."
    git diff --exit-code
  container:
    from: get-collections
- as: aws-arm-cluster
  steps:
    cluster_profile: aws-3
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: release:arm64-latest
    env:
      OCP_ARCH: arm64
    test:
    - as: pre-notifier
      commands: curl -d "Cluster is ready for https://github.com/${REPO_OWNER}/${REPO_NAME}/pull/${PULL_NUMBER}"
        ntfy.sh/notify-chiragkyal
      from: src
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
    - as: sleeper
      commands: |
        #!/bin/bash
        total_duration=21300 # 5h55m, timeout is 6h
        elapsed_time=0
        while [ $elapsed_time -lt $total_duration ]; do
            sleep 30
            elapsed_time=$((elapsed_time + 30))
            echo "Elapsed time: $((elapsed_time / 3600)) hours $(((elapsed_time % 3600) / 60)) minutes $((elapsed_time % 60)) seconds"
        done
      from: src
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
      timeout: 6h0m0s
    - as: post-notifier
      commands: curl -d "cluster about to be destroyed for https://github.com/${REPO_OWNER}/${REPO_NAME}/pull/${PULL_NUMBER}"
        ntfy.sh/notify-chiragkyal
      from: src
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
    workflow: ipi-aws
  timeout: 7h0m0s
zz_generated_metadata:
  branch: main
  org: openshift
  repo: ansible-operator-plugins
